language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script: 
  - curl --silent http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-dist

notifications:
  email: joris.w.dewit@gmail.com
